TEST:
  FROM_TEMP: false
  SAVE_NAME: vortex_128_safecirclec0
  SETTING: vortex

MESH:
  GRID_SIZE: 100
  RESOLUTION: 1.28

GEOMS:
  FACET_ALGO: safe_circle
  THRESHOLD: 1.0e-10
  DO_C0: true

ADVECTION:
  DO_ADVECT: true
  DT: 0.01
  T_TOTAL: 2